/**
 * Created by chengtao on 2018/6/22/022.
 */
var ANCHOR_CONF = [
    {
        key:'cfg_rssi_threshold',
        value:-95,
        des:lang['cfg_rssi_threshold']
    },
    {
        key:'cfg_plos_threshold',
        value:-3,
        des:lang['cfg_plos_threshold']
    },
    {
        key:'cfg_priority',
        value:0,
        des:'选组优先级，值越大优先级越高'
    },
    {
        key:'cfg_diff_divide',
        value:0.95,
        des:'距离差的绝对值除以两基站之间的距离，大于此阈值距离差将会被过滤'
    },
    {
        key:'cfg_tof_0d_threshold',
        value: 5,
        des:lang['cfg_tof_0d_threshold']
    },
    {
        key:'cfg_rxFP_threshold',
        value:35,
        des:lang['cfg_rxFP_threshold']
    },
    {
        key:'cfg_IDiff_threshold',
        value:400,
        des:lang['cfg_IDiff_threshold']
    },
    {
        key:'cfg_mc_threshold',
        value:10,
        des:lang['cfg_mc_threshold']
    },
    {
        key:'cfg_plos_is_no_filter',
        value:0,
        des:lang['cfg_plos_is_no_filter']
    },
    {
        key:'cfg_tof_offset',
        value:0,
        des:lang['cfg_tof_offset']
    },
    {
        key:'cfg_x_offset',
        value:0,
        des:lang['cfg_x_offset']
    },
    {
        key:'cfg_y_offset',
        value:0,
        des:lang['cfg_y_offset']
    },
    {
        key:'cfg_rate_offset',
        value:0,
        des:lang['cfg_rate_offset']
    },
    {
        key:'cfg_no_master_group',
        value:0,
        des:lang['cfg_no_master_group']
    },
    {
        key:'cfg_master_group_zone_id',
        value:0,
        des:lang['cfg_master_group_zone_id']
    },
    {
        key:'cfg_tdoa1d_width',
        value:1.2,
        des:'一维定位区域宽度'
    },
    {
        key:'cfg_forceSelectAlone',
        value:0,
        des:lang['cfg_forceSelectAlone']
    },
]